


# ------------------------------------------------------------------------------
# -----------------------------mpv-uosc-control-configuration-------------------
# 参考 https://blog.hentioe.dev/posts/mpv-uosc-control-configuration.html
# ------------------------------------------------------------------------------


# 播放与暂停
# 默认情况下，MPV 不会在按下空格键（即播放/暂停）时显示 OSD 或动画。这很不直观。通过配置 input.conf 文件中的快捷键，我们覆盖这个操作，让它显示 OSD 或动画：
space           cycle pause; script-binding uosc/decide-pause-indicator
MBTN_RIGHT      cycle pause; script-binding uosc/flash-pause-indicator

pause_indicator=manual

# 前进与后退
# 默认按下前进（右方向键）和后退（左方向键）时，uosc/MPV 不会显示任何东西。这也是不符合操作直觉的，因为我们普遍需要在前进和后退时知晓当前进度信息。
right           seek  5; script-binding uosc/flash-timeline
left            seek -5; script-binding uosc/flash-timeline
up              seek  60; script-binding uosc/flash-timeline
down            seek -60; script-binding uosc/flash-timeline
shift+right     seek  1; script-binding uosc/flash-timeline
shift+left      seek -1; script-binding uosc/flash-timeline

# 音量调整
# 默认使用滚轮上/下调整音量时，不会显示 usoc 的音量控制器。如果你没有隐藏 OSD 栏，它会显示 MPV 的音量条。即使你隐藏了，左上角的音量数值文字仍会显示。这显然和 uosc 是有些格格不入的。让我们编辑 input.conf 覆盖它：
wheel_up        no-osd add volume  2; script-binding uosc/flash-volume
wheel_down      no-osd add volume -2; script-binding uosc/flash-volume

# 静音
# 现在在显示 UI 的同时，你能从音量控制器下方喇叭图标判断静音状态（被斜杠划掉表示静音）。
m               no-osd cycle mute; script-binding uosc/flash-volume

# 播放速度
# 默认情况下 MPV 按下 [ 和 ] 调整播放速度时，我们也看不到 uosc 的指示器。让我们编辑 input.conf 覆盖相关操作：
[               no-osd add speed -0.25; script-binding uosc/flash-speed
]               no-osd add speed  0.25; script-binding uosc/flash-speed
BS              no-osd set speed 1; script-binding uosc/flash-speed

# 在播放列表中切换
# 这是 uosc 官方推荐添加的配置。编辑 input.conf 覆盖默认操作：
>               script-binding uosc/next; script-message-to uosc flash-elements top_bar,timeline
<               script-binding uosc/prev; script-message-to uosc flash-elements top_bar,timeline

# 上下文菜单
# uosc 提供了一套上下文菜单，点击左下角的菜单图标显示。常规来讲，符合直觉的触发方式是右键点击，但我认为右键双击更好（原因下面会说）。编辑 input.conf 添加这个操作：
MBTN_RIGHT_DBL  script-binding uosc/menu

tab  script-binding uosc/menu

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------