# uosc 提供跳转和音量指示器（通过 flash-timeline 和 flash-volume 命令）
# 如果你决定使用它们，就不需要 osd-bar 了
osd-bar=no

# 如果你禁用窗口边框，uosc 会绘制自己的窗口控件和边框
border=no


# 视频同步模式，使用显示重采样以减少画面撕裂
video-sync=display-resample

# 硬件加速（Windows 通用）
hwdec=d3d11va-copy
d3d11va-zero-copy=yes
gpu-context=d3d11

# 线程与性能
num-threads=4
demuxer-thread=yes