[shortcuts]
focusSearch.label=聚焦搜索框
focusSearch.keys=ctrl+f,ctrl+l
clearSearch.label=取消搜索聚焦
clearSearch.keys=escape
goBack.label=返回上一页
goBack.keys=alt+arrowleft,alt+arrowright
openDevTools.label=打开开发者工具
openDevTools.keys=f12
openSettings.label=打开设置
openSettings.keys=ctrl+,
openShortcutSettings.label=打开快捷键设置
openShortcutSettings.keys=ctrl+shift+,
closeWindow.label=关闭窗口/弹出框
closeWindow.keys=q
