[shortcuts]

focusSearch.label=聚焦搜索框
focusSearch.keys=ctrl+f,ctrl+l,/
clearSearch.label=取消搜索聚焦
clearSearch.keys=escape
openDevTools.label=打开开发者工具
openDevTools.keys=F1
openSettings.label=打开设置
openSettings.keys=ctrl+,
openShortcutSettings.label=打开快捷键设置
openShortcutSettings.keys=ctrl+shift+,

# vim风格快捷键
triggerAction.label=触发动作
triggerAction.keys=f
scrollDown.label=向下翻半页
scrollDown.keys=d
scrollUp.label=向上翻半页
scrollUp.keys=e
goTop.label=回到顶部
goTop.keys=g+g
goBack.label=返回上一页
goBack.keys=escape,u
refresh.label=刷新当前页
refresh.keys=r
closeWindow.label=关闭窗口/弹出框
closeWindow.keys=q